### ISSUE TITLE
STAC Copy not working with relative link.

### ISSUE THREAD

**Issue by cholmes** [stac-utils/stactools#168]
Ok, I'm breaking out the issue from  https://github.com/stac-utils/stactools/pull/151#issuecomment-882812752_ into it's own issue, as I think I have the failure with just a copy command.

[test-catalog.zip](https://github.com/stac-utils/stactools/files/6843641/test-catalog.zip) is a test catalog that shows the problem.

If I do a `stac copy` with the test catalog I get a failure of it not finding the file. But if I make edit the item link href to be an absolute URL with the path on my computer then it works just fine. So it seems like stac copy is not reading the path relatively. The error is:

```
 File "/Users/cholmes/Repos/stactools-pete/venv/lib/python3.7/site-packages/fsspec/core.py", line 102, in __enter__
    f = self.fs.open(self.path, mode=mode)
  File "/Users/cholmes/Repos/stactools-pete/venv/lib/python3.7/site-packages/fsspec/spec.py", line 968, in open
    **kwargs,
  File "/Users/cholmes/Repos/stactools-pete/venv/lib/python3.7/site-packages/fsspec/implementations/local.py", line 144, in _open
    return LocalFileOpener(path, mode, fs=self, **kwargs)
  File "/Users/cholmes/Repos/stactools-pete/venv/lib/python3.7/site-packages/fsspec/implementations/local.py", line 235, in __init__
    self._open()
  File "/Users/cholmes/Repos/stactools-pete/venv/lib/python3.7/site-packages/fsspec/implementations/local.py", line 240, in _open
    self.f = open(self.path, mode=self.mode)
FileNotFoundError: [Errno 2] No such file or directory: '/20201211_103040_ssc12_u0001/20201211_103040_ssc12_u0001.json'
```

Which seems to indicate that it thinks it's an absolute path...

**Comment by cholmes** [comment]
Further testing reveals that it's fine to do a stac copy from a remote location. But then trying to do a copy locally results in the exact same types of errors:

```
cholmes@c02y3151jhd3 tc % stac copy https://storage.googleapis.com/open-cogs/planet-stac/collection.json local
cholmes@c02y3151jhd3 tc % cd local 
cholmes@c02y3151jhd3 local % stac copy collection.json test
Traceback (most recent call last):
  File "/Users/cholmes/.local/bin/stac", line 8, in <module>
    sys.exit(run_cli())
  File "/Users/cholmes/.local/lib/python3.7/site-packages/stactools/cli/cli.py", line 40, in run_cli
    cli(prog_name='stac')
  File "/Users/cholmes/.local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/cholmes/.local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/cholmes/.local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/cholmes/.local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/cholmes/.local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/cholmes/.local/lib/python3.7/site-packages/stactools/cli/commands/copy.py", line 67, in copy_command
    copy_catalog(source_catalog, dst, catalog_type, copy_assets)
  File "/Users/cholmes/.local/lib/python3.7/site-packages/stactools/core/copy.py", line 198, in copy_catalog
    catalog = source_catalog.full_copy()
  File "/Users/cholmes/.local/lib/python3.7/site-packages/pystac/collection.py", line 679, in full_copy
    return cast(Collection, super().full_copy(root, parent))
  File "/Users/cholmes/.local/lib/python3.7/site-packages/pystac/catalog.py", line 954, in full_copy
    return cast(Catalog, super().full_copy(root, parent))
  File "/Users/cholmes/.local/lib/python3.7/site-packages/pystac/stac_object.py", line 372, in full_copy
    link.resolve_stac_object()
  File "/Users/cholmes/.local/lib/python3.7/site-packages/pystac/link.py", line 213, in resolve_stac_object
    obj = stac_io.read_stac_object(target_href, root=root)
  File "/Users/cholmes/.local/lib/python3.7/site-packages/pystac/stac_io.py", line 172, in read_stac_object
    d = self.read_json(source)
  File "/Users/cholmes/.local/lib/python3.7/site-packages/pystac/stac_io.py", line 151, in read_json
    txt = self.read_text(source, *args, **kwargs)
  File "/Users/cholmes/.local/lib/python3.7/site-packages/pystac/stac_io.py", line 215, in read_text
    return self.read_text_from_href(href, *args, **kwargs)
  File "/Users/cholmes/.local/lib/python3.7/site-packages/stactools/core/io/__init__.py", line 24, in read_text_from_href
    with fsspec.open(href, "r") as f:
  File "/Users/cholmes/.local/lib/python3.7/site-packages/fsspec/core.py", line 102, in __enter__
    f = self.fs.open(self.path, mode=mode)
  File "/Users/cholmes/.local/lib/python3.7/site-packages/fsspec/spec.py", line 968, in open
    **kwargs,
  File "/Users/cholmes/.local/lib/python3.7/site-packages/fsspec/implementations/local.py", line 132, in _open
    return LocalFileOpener(path, mode, fs=self, **kwargs)
  File "/Users/cholmes/.local/lib/python3.7/site-packages/fsspec/implementations/local.py", line 220, in __init__
    self._open()
  File "/Users/cholmes/.local/lib/python3.7/site-packages/fsspec/implementations/local.py", line 225, in _open
    self.f = open(self.path, mode=self.mode)
FileNotFoundError: [Errno 2] No such file or directory: '/angkor-wat/catalog.json'
```

Ok, something quite weird is going on. The above fails, but if I don't cd into the directory then the copy works fine:

```
cholmes@c02y3151jhd3 tc % stac copy https://storage.googleapis.com/open-cogs/planet-stac/collection.json local
cholmes@c02y3151jhd3 tc % stac copy local/collection.json test
```

Works fine? It seems to just be if you're in the same directory as the collection.json you're trying to copy?

**Comment by cuttlefish** [comment]
Explicitly specifying `./collection.json` seems to work properly.
Using `make_absolute_href` to force an absolute path seems to work here. I'm unsure if it will cause problems elsewhere.
https://github.com/stac-utils/stactools/blob/35f61316bde3eb46295d02d6239bdc6d5f46b4ec/src/stactools/cli/commands/copy.py#L66

**Comment by cholmes** [comment]
And for versions I'm testing:
```
cholmes@c02y3151jhd3 tc % stac version
stactools version 0.2.1a1
PySTAC version 1.0.0
```

And I also tested directly from Pete's stac validate branch: https://github.com/gadomski/stactools/tree/feature/stac-validate

**Comment by cholmes** [comment]
Potentially related is another error I have got a number of times on 'merge':

```
cholmes@c02y3151jhd3 new-stacs % stac merge sp-crater-sr/collection.json sp-crater/collection.json --move-assets --ignore-conflicts
Traceback (most recent call last):
  File "/Users/cholmes/.local/bin/stac", line 8, in <module>
    sys.exit(run_cli())
  File "/Users/cholmes/.local/lib/python3.7/site-packages/stactools/cli/cli.py", line 40, in run_cli
    cli(prog_name='stac')
  File "/Users/cholmes/.local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/cholmes/.local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/cholmes/.local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/cholmes/.local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/cholmes/.local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/cholmes/.local/lib/python3.7/site-packages/stactools/cli/commands/merge.py", line 66, in merge_command
    child_folder=child_folder)
  File "/Users/cholmes/.local/lib/python3.7/site-packages/stactools/cli/commands/merge.py", line 26, in merge
    child_folder)
  File "/Users/cholmes/.local/lib/python3.7/site-packages/stactools/core/merge.py", line 113, in merge_all_items
    ignore_conflicts=ignore_conflicts)
  File "/Users/cholmes/.local/lib/python3.7/site-packages/stactools/core/merge.py", line 44, in merge_items
    target_item, asset_href, ignore_conflicts=ignore_conflicts)
  File "/Users/cholmes/.local/lib/python3.7/site-packages/stactools/core/copy.py", line 43, in move_asset_file_to_item
    raise ValueError('asset_href msut be absolute.')
ValueError: asset_href msut be absolute.
```

I can file that as its own issue and try to get to something that's easy to reproduce if it feels totally different. But it's one where I'm following along just like https://stactools.readthedocs.io/en/latest/tutorials/working-with-planet-data-in-the-cli.html says but with my own orders and I get the error.

**Comment by volaya** [comment]
I confirm that I can reproduce the error. I don't think that forcing the absolute path as @cuttlefish suggest will have any side effeccts, but i guess it's better to fix in on the pystac code, because the issue seem to be there, in how it handles that sort of paths. So better to fix the root of the issue instead of changin how stactools calls it.  I will work on it. Let me know if you have any other idea or anything else to add to this ticket

**Comment by cholmes** [comment]
Fixing it in pystac sounds right, thanks!

**Comment by gadomski** [comment]
FYSA I also opened https://github.com/stac-utils/pystac/issues/571 this morning regarding the incorrect assumption that `get_self_href` always returns absolute links (it doesn't if a relative link is passed in to `pystac.read_item` or similar functions). I don't know if it's related to this issue but it sure could be.

**Comment by gadomski** [comment]
I can confirm that this issue is caused by stac-utils/pystac#571, due to the owner's self href being relative here: https://github.com/stac-utils/pystac/blob/main/pystac/link.py#L234.

<img width="1552" alt="Screen Shot 2021-07-20 at 11 46 25 AM" src="https://user-images.githubusercontent.com/58314/126378639-7448fa9e-7581-47d9-8f5f-65cda6057861.png">

**Comment by volaya** [comment]
Good catch. In any case, maybe it doesn't hurt to add what @cuttlefish suggest, because i have seen that the copy operation converts the destination folder into a absolute href (see https://github.com/stac-utils/stactools/blob/main/src/stactools/core/copy.py#L199) before saving it, so maybe it makes sense to call make_absolute_href also when loading the catalog, to have both paths treated the same way

**Comment by gadomski** [comment]
@cholmes can you try again with latest **main** branch? It looks like this issue is fixed from my side.

**Comment by cholmes** [comment]
Works on my test case testing locally! I'll try it out a bit more, but it looks like it should be good.

**Comment by cholmes** [comment]
Trying out a few more things, the copy seems to work. I did just try 'move-assets' and it seemed to fail similarly - didn't work if you are in the directory with the catalog/collection, but does if you're one down. I can try to make a reproducable test case if that helps.

Also it'd be really great if someone could look at https://github.com/stac-utils/stactools/issues/169 as it seems to be a similar type of problem (and is the one that is most blocking me right now).

**Comment by gadomski** [comment]
@cholmes per https://github.com/stac-utils/stactools/issues/169#issuecomment-886984940 you might be good to go, so if you can test again and let us know if things are still broken that'd be great. Same with the `move-assets`, if you can see if that's still broken with PySTAC v1.0.1 that'd be swell. Thanks!

**Comment by cholmes** [comment]
Looks like it works, thanks!
