### ISSUE TITLE
stac merge error: 'raise ValueError('asset_href msut be absolute.')'

### ISSUE THREAD

**Issue by cholmes** [stac-utils/stactools#169]
Pulling this out as its own issue from https://github.com/stac-utils/stactools/issues/168#issuecomment-882907123_ as I verified you get the exact same problem if you simply follow the [tutorial on using Planet data with CLI](https://stactools.readthedocs.io/en/latest/tutorials/working-with-planet-data-in-the-cli.html).

Basically when you do the stac merge command with planet data it gets the below error. This seems like a regression, as I've done the tutorial before, and tried it again with the 0.2.x stactools and it got the exact same error.

```
stac merge planet-stacs/analytic/collection.json planet-stacs/visual/collection.json --move-assets --ignore-conflicts 

Traceback (most recent call last):
  File "/Users/cholmes/.local/bin/stac", line 8, in <module>
    sys.exit(run_cli())
  File "/Users/cholmes/.local/lib/python3.7/site-packages/stactools/cli/cli.py", line 40, in run_cli
    cli(prog_name='stac')
  File "/Users/cholmes/.local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/cholmes/.local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/cholmes/.local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/cholmes/.local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/cholmes/.local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/cholmes/.local/lib/python3.7/site-packages/stactools/cli/commands/merge.py", line 66, in merge_command
    child_folder=child_folder)
  File "/Users/cholmes/.local/lib/python3.7/site-packages/stactools/cli/commands/merge.py", line 26, in merge
    child_folder)
  File "/Users/cholmes/.local/lib/python3.7/site-packages/stactools/core/merge.py", line 113, in merge_all_items
    ignore_conflicts=ignore_conflicts)
  File "/Users/cholmes/.local/lib/python3.7/site-packages/stactools/core/merge.py", line 44, in merge_items
    target_item, asset_href, ignore_conflicts=ignore_conflicts)
  File "/Users/cholmes/.local/lib/python3.7/site-packages/stactools/core/copy.py", line 43, in move_asset_file_to_item
    raise ValueError('asset_href msut be absolute.')
ValueError: asset_href msut be absolute.
(venv) cholmes@c02y3151jhd3 tutorial % 
```

**Comment by gadomski** [comment]
@cholmes is it possible to get an isolated set of test data to reproduce this issue? I've tried to hack one together just w/ stactools w/o success, and it'd be good to have an example that doesn't require a Planet login. Thanks!

**Comment by cholmes** [comment]
Yeah. I'll just zip up what I have and stick on a cloud, as it'll be big with the files in it.

**Comment by gadomski** [comment]
@cholmes I _believe_ that https://github.com/stac-utils/pystac/pull/574 will resolve this issue. Once PySTAC v1.0.1 is released, we can release a new alpha of stactools for you to try.

**Comment by cholmes** [comment]
Ok, great. Happy to test it. Would be great to get #151 in for the release to have the 'validate' command there too.

**Comment by gadomski** [comment]
@cholmes PySTAC v1.0.1 is released and a fresh install of **stactools** should automatically pick it up. If you have an existing environment, you can do `pip install -U pystac` to update to v1.0.1 and test to see if your issue is fixed.

**Comment by cholmes** [comment]
Seems to work, thank you!
