### ISSUE TITLE
Display the name of the file where a validation error occurred. 

### ISSUE THREAD

**Issue by cholmes** [stac-utils/stactools#51]
stac tools is useful for doing validation, but it can be hard to see exactly where things went wrong. 

I'm using `stac info` (maybe there's a better one to use), and on a 3 item catalog I get:

```
Traceback (most recent call last):
  File "/Users/cholmes/.local/bin/stac", line 8, in <module>
    sys.exit(run_cli())
  File "/Users/cholmes/.local/lib/python3.7/site-packages/stactools/cli/cli.py", line 40, in run_cli
    cli(prog_name='stac')
  File "/Users/cholmes/.local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/cholmes/.local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/cholmes/.local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/cholmes/.local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/cholmes/.local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/cholmes/.local/lib/python3.7/site-packages/stactools/cli/commands/info.py", line 49, in info_command
    print_info(catalog_path)
  File "/Users/cholmes/.local/lib/python3.7/site-packages/stactools/cli/commands/info.py", line 23, in print_info
    for item in items:
  File "/Users/cholmes/.local/lib/python3.7/site-packages/pystac/stac_object.py", line 372, in get_stac_objects
    link.resolve_stac_object(root=self.get_root())
  File "/Users/cholmes/.local/lib/python3.7/site-packages/pystac/link.py", line 166, in resolve_stac_object
    obj = STAC_IO.read_stac_object(target_href, root=root)
  File "/Users/cholmes/.local/lib/python3.7/site-packages/pystac/stac_io.py", line 130, in read_stac_object
    d = cls.read_json(uri)
  File "/Users/cholmes/.local/lib/python3.7/site-packages/pystac/stac_io.py", line 108, in read_json
    return json.loads(STAC_IO.read_text(uri))
  File "/opt/salt/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/opt/salt/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/salt/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 54 column 3 (char 1122)
```

Very useful to tell me the exact place in the file that is messed up. But I don't see which file it is, I have to hunt through all of them. Some chance this is user error, but it'd be good to pop up the file where things messed up. Or maybe it's easier to just make a `stac validate` command that can be more informative? And then errors on other operations can tell you to use stac validate.

**Comment by cholmes** [comment]
I'm encountering similarly tough situations with 'file not found' when I'm trying copy or moving of assets. I know it's something that is off in my catalog, as it's been hacked together. But I don't even getting the line and column, just a 'no such file', but I'm not sure what file the errors is on:

```
  File "/Users/cholmes/Repos/planet-orders/venv/lib/python3.7/site-packages/pystac/stac_io.py", line 215, in read_text
    return self.read_text_from_href(href, *args, **kwargs)
  File "/Users/cholmes/Repos/planet-orders/venv/lib/python3.7/site-packages/stactools/core/io/__init__.py", line 24, in read_text_from_href
    with fsspec.open(href, "r") as f:
  File "/Users/cholmes/Repos/planet-orders/venv/lib/python3.7/site-packages/fsspec/core.py", line 102, in __enter__
    f = self.fs.open(self.path, mode=mode)
  File "/Users/cholmes/Repos/planet-orders/venv/lib/python3.7/site-packages/fsspec/spec.py", line 968, in open
    **kwargs,
  File "/Users/cholmes/Repos/planet-orders/venv/lib/python3.7/site-packages/fsspec/implementations/local.py", line 132, in _open
    return LocalFileOpener(path, mode, fs=self, **kwargs)
  File "/Users/cholmes/Repos/planet-orders/venv/lib/python3.7/site-packages/fsspec/implementations/local.py", line 220, in __init__
    self._open()
  File "/Users/cholmes/Repos/planet-orders/venv/lib/python3.7/site-packages/fsspec/implementations/local.py", line 225, in _open
    self.f = open(self.path, mode=self.mode)
FileNotFoundError: [Errno 2] No such file or directory: '/20201230_151832_ssc13_u0002/20201230_151832_ssc13_u0002.json'
```
